steps:
  # Step 1: Fetch the service account key from Secret Manager and authenticate
  - name: 'gcr.io/cloud-builders/gcloud'
    id: setup-credentials
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=prod-gcp-sa-key > /workspace/key.json
        gcloud auth activate-service-account --key-file=/workspace/key.json

  # Step 2: Install Terraform and initialize
  - name: 'hashicorp/terraform:1.5.0'
    id: init
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd Environments/Production
        terraform init

  # Step 3: Terraform Plan
  - name: 'hashicorp/terraform:1.5.0'
    id: plan
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd Environments/Production
        terraform plan -out=tfplan

  # Step 4: Manual Approval
  - name: 'gcr.io/cloud-builders/gcloud'
    id: approval
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Waiting for manual approval..."
    waitFor: ['plan']

  # Step 5: Terraform Apply (after approval)
  - name: 'hashicorp/terraform:1.5.0'
    id: apply
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd Environments/Production
        terraform apply -auto-approve tfplan
    waitFor: ['approval']

timeout: 1200s

substitutions:
  _STAGING_PROJECT_ID: "technosynz-prod"
  _REGION: "us-central1"

options:
  env:
    - TF_VAR_project_id=${_STAGING_PROJECT_ID}
    - TF_VAR_region=${_REGION}
  logging: GCS_ONLY

logsBucket: 'gs://technosynz-prod-cloudbuild-logs'  # Specify the bucket for logs